[package]
name = "lg600r"
version = "0.1.0"
authors = ["Zoey <Dessix@Dessix.net>"]

[dependencies]
maplit = "1.0.1"
toml = "0.4.6"
xdg = "^2.1"

[build-dependencies]
bindgen = "*"

[features]
default = []

idebuild = []